### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by lolicem** [Vap0r1ze/Jewel#1]
Your file structure looks like the big trash.

**Comment by Vap0r1ze** [comment]
![image](https://user-images.githubusercontent.com/20448879/43876414-eecd421e-9b62-11e8-842f-bcedfae67e35.png)

**Comment by lolicem** [comment]
Create an `incl` folder and put `util` & `plugins` into it, and i'll be happy.

**Comment by Vap0r1ze** [comment]
where is that a standard
